# ansible-infrastructure-playbook  
---
  - name: Creating User ----- Please wait
    community.aws.iam:
      iam_type: user
      name: "{{ item }}"
      state: present
      password: "evolvecyberevolvecyberevolvecyberevolvecyberevolvecyber1!"
      access_key_state: create
    loop:
      - DevOps_Student1
    
      

  - name: Creating a DevOps group --- Please wait
    community.aws.iam:
      iam_type: group
      name: "{{ item }}"
      state: present
    loop:
     - DevOps
    register: DevOps