# ansible-playbook IAAC/ec2.yaml 
---
  - amazon.aws.ec2:
      key_name: laptop
      instance_type: t2.micro
      image: ami-074cce78125f09d61
      wait: yes
      count: 5
      region: us-east-2