galaxy_info:
  author: emirsway
  description: Automate Wordpress deployment in Ubuntu
  company: N/A
  license: "Check License.md"

  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Fedora
    versions:
     - all
  - name: EL
    versions:
    - all
  - name: Debian
    versions:
    - all
  #   - 1.0
  #   - 7
  #   - 99.99

  categories:
  - development
  - web
  galaxy_tags: 
  - wordpress
  - cms


