---
# tasks file for Ubuntu and Debian
- name: Install required software
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - build-essential
    - python-dev
    - libmysqlclient-dev
    - mysql-server
    - mysql-client
    - python3-dev
    - python3-mysqldb
- name: Ubuntu and Debian start apache service
  service: name=apache2 state=started
- name: Create database
  include: mysqldb.yml
- name: Download and extract wordpress
  include: wpdownload.yml